config/routes.rb
Rails.application.routes.draw do
  root 'bills#index'
  get 'clients', to: 'users#clients'
  get 'clients/new', to: 'users#new_client'

  resources :bills
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_one_attached :file
  validate :file_validation

  def file_validation
    if file.attached?
      if file.blob.byte_size > 1000000
        file.purge
        errors[:base] << 'Archivo demasiado grande'
      elsif !file.blob.content_type.starts_with?('application/pdf')
        file.purge
        errors[:base] << 'Formato incorrecto. Debes elegir un archivo pdf'
      end
    else
      errors[:base] << 'Debes seleccionar un archivo PDF'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :bills
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable


  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = current_user.bills.build(bill_params)
    @bill.do_payment_at = nil
    @bill.paid_at = nil

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:file, :do_payment_at, :details, :paid_at, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.where(admin: true)
  end

  def clients
    @users = User.where(admin: false)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new(admin: true)
  end

  def new_client
    @user = User.new(admin: false)
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { 
          redirect_to users_url, notice: 'El usuario fue registrado exitosamente.' if @user.admin?
          redirect_to clients_url, notice: 'El cliente fue registrado exitosamente.'
        }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { 
          render :new if @user.admin?
          render :new_client
        }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :admin, :email, :password, :password_confirmation )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/_form.html.erb
<%= form_with(model: bill, local: true) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin %>

    <div class="field">
      <%= form.label :do_payment_at, 'Hacer el pago el' %>
      <%= form.date_select :do_payment_at, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :details, 'Mas detalles' %>
      <%= form.text_area :details, class: 'form-control' %>
    </div>

    <!-- <div class="field">
      <%#= form.label :paid_at %>
      <%#= form.date_select :paid_at %>
    </div>

    <div class="field">
      <%#= form.label :user_id %>
      <%#= form.text_field :user_id %>
    </div> -->
  <% end %>

  <% if current_user.admin %>
    <br>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>

  <% unless current_user.admin  %>
    <% if bill.do_payment_at.present? %>
      <div class="field">
      <%= form.label :paid_at, 'Pagada el' %>
      <%= form.date_select :paid_at, class: 'form-control' %>
    </div>
    <% else %>
      <div class="field">
        <%= form.label :file, 'Archivo' %>
        <%= form.file_field :file, accept: 'application/pdf' %>
      </div>
    <% end %>
  <% else %>
    <!-- <p>
      <strong>File:</strong>
      <%#= image_tag @bill.file %>
    </p> -->
  <% end %>

  <br>
  <% unless current_user.admin %>
    <br>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/bills/edit.html.erb
<div class="container">
  <br><br>
  <h1>Editando Factura</h1>

  <%= render 'form', bill: @bill %>

  <%= link_to 'Ver', @bill %> |
  <%= link_to 'Atras', bills_path %>
</div>

app/views/bills/index.html.erb
<div class="container">
  
  <br><br>

  <div class="row">
    <div class="col-sm-8">
      <h1>Facturas</h1>
    </div>

    <div class="col-sm-4 text-right">
      <%= link_to '+ Factura', new_bill_path, class: 'btn btn-primary' %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Subida el</th>
        <th>Hacer pago el</th>
        <th>Detalles</th>
        <th>Pagado el</th>
        <th>Cliente</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @bills.each do |bill| %>
        <tr>
          <td><%= bill.created_at %></td>
          <td>
            <% if bill.do_payment_at.present? %>
              <span class="badge badge-info"><%= bill.do_payment_at %></span>    
            <% else %>
              <span class="badge badge-secondary">Pendiente</span>
            <% end %>
          </td>
          <td><%= bill.details %></td>
          <td>
            <% if bill.paid_at.present? %>
              <%= bill.paid_at %>
            <% else %>
              <span class="badge badge-warning">No pagada</span>
            <% end %>
          </td>
          <td><%= bill.user.email %></td>
            <td><%= link_to 'PDF', bill.file, target: '_blank' %></td>
            <!-- <td><%#= link_to 'Show', bill %></td> -->

          <% if current_user.admin? %>
            <td><%= link_to 'Revisar', edit_bill_path(bill) %></td>
          <% else %>
            <td><%= link_to 'Registrar pago', edit_bill_path(bill) if bill.do_payment_at.present? %></td>
          <% end %>

          <td><%= link_to 'Eliminar', bill, method: :delete, data: { confirm: 'Are you sure?' }  if current_user.admin == false && !bill.do_payment_at.present? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/bills/new.html.erb
<div class="container">
  
  <h1>Nueva factura</h1>

  <%= render 'form', bill: @bill %>

  <%= link_to 'Back', bills_path %>
</div>

app/views/bills/show.html.erb
<div class="container">
  <br><br>
  <div>

    <p>
      <strong>Factura:</strong>
      <%= link_to 'Ver PDF', @bill.file, target: '_blank' %>
    </p>
    
    <p>
      <strong>Debes realiza tu pago el dia: </strong>
      <%= @bill.do_payment_at.present? ? @bill.do_payment_at : 'Pronto te diremos cuando' %>
    </p>
    <% if @bill.details.present? %>
      <p>
        <strong>Mas detalles:</strong>
        <%= @bill.details %>
      </p>
    <% end %>
  </div>


  <!-- <p>
    <strong>Paid at:</strong>
    <%#= @bill.paid_at %>
  </p> -->

  <p><!-- 
    <%#= image_tag @bill.file, width: '900px' %>
  </p> -->


  <p>
    <strong>Usuario:</strong>
    <%= @bill.user.name %>
  </p>

  <%#= link_to 'Editar', edit_bill_path(@bill) %>
  <%= link_to 'Atras', bills_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'partials/navbar' %>
    <% end %>
    
    <% if notice %>
      <div class="alert alert-info text-center" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning text-center" role="alert">
        <%= alert %>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<% if current_user.admin? %>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="#"><strong>FactHelp</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Facturas', bills_path, class: 'nav-item nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Clientes', clients_path, class: 'nav-item nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Usuarios', users_path, class: 'nav-item nav-link' %>
        </li>
      </ul>
      <span class="navbar-text">
        <%= current_user.email %> | <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'btn btn-alert' %>
      </span>
    </div>
  </nav>

<% else %>

  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="#"><strong>FactHelp</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Mis Facturas', bills_path, class: 'nav-item nav-link' %>
        </li>
      </ul>
      <span class="navbar-text">
        <%= current_user.email %> | <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: 'btn btn-alert' %>
      </span>
    </div>
  </nav>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: 'was-validated') do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.hidden_field :admin, value: @user.admin %>
  </div>

  <div class="form-group">
    <%= form.label :email %><br />
    <%= form.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %><br />
    <%= form.password_field :password, autocomplete: "current-password", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation, autocomplete: "current-password", class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/clients.html.erb
<div class="container">
  
  <h1>Clientes</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= link_to 'Ver', user %></td>
          <td><%= link_to 'Editar', edit_user_path(user) %></td>
          <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  
  <div class="row">
    <div class="col-sm-12 text-center">
      
      <%= link_to '+ Nuevo Cliente', clients_new_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new_client.html.erb
<div class="container">
  <h1>Nuevo cliente</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Atras', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>